# Generated by Django 4.0.1 on 2022-02-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2b', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lnmtransaction',
            name='trans_amount',
        ),
        migrations.AddField(
            model_name='lnmtransaction',
            name='transaction_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='lnmtransaction',
            name='org_account_balance',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
