# Generated by Django 4.0.1 on 2022-02-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2b', '0002_remove_lnmtransaction_trans_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lnmtransaction',
            name='transaction_id',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
