# Generated by Django 4.0.1 on 2022-02-03 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c2b', '0004_lnmtransaction_confirmation_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lnmtransaction',
            name='first_name',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lnmtransaction',
            name='invoice_number',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lnmtransaction',
            name='last_name',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lnmtransaction',
            name='middle_name',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lnmtransaction',
            name='third_party_trans_id',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='lnmtransaction',
            name='transaction_status',
            field=models.TextField(max_length=30, null=True),
        ),
    ]
