# Generated by Django 4.0.1 on 2022-02-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnm_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lnmtransaction',
            name='confirmation_request_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='lnmtransaction',
            name='validation_request_time',
            field=models.DateTimeField(null=True),
        ),
    ]
